name: Bearer Scan

on:
  pull_request:
    types: [opened]

permissions:
  contents: read # Minimal permissions

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Run Bearer
        uses: bearer/actions@main
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          BEARER_HOST: ${{ secrets.BEARER_HOST }}
